export class ColumnsPagosEmiConciliados {
  columns_header: Array<{ title: string, data: string }>;

  constructor() {
    this.columns_header = [
      { title: 'ESTATUS SAT', data: '0' },
      { title: 'FECHA CANCELACIÓN SAT', data: '1' },
      { title: 'FOLIO FISCAL SAT', data: '2' },
      { title: 'RFC EMISOR SAT', data: '3' },
      { title: 'RAZÓN SOCIAL EMISOR SAT', data: '4' },
      { title: 'RFC RECEPTOR SAT', data: '5' },
      { title: 'RAZÓN SOCIAL RECEPTOR SAT', data: '6' },
      { title: 'RFC PAC SAT', data: '7' },
      { title: 'FECHA EMISION SAT (YYYY-MM-DD)', data: '8' },
      { title: 'FECHA EMISION SAT', data: '9' },
      { title: 'FECHA TIMBRADO SAT', data: '10' },
      { title: 'MONTO DE PAGO SAT', data: '11' },
      { title: 'EFECTO COMPROBANTE SAT', data: '12' },
      { title: 'USO DE CFDI SAT', data: '13' },
      { title: 'CÓDIGO POSTAL EMISOR SAT', data: '14' },
      { title: 'FOLIO SAT', data: '15' },
      { title: 'SERIE SAT', data: '16' },
      { title: 'FECHA PAGO SAT (YYYY-MM-DD)', data: '17' },
      { title: 'FORMA DE PAGO SAT ', data: '18' },
      { title: 'MONEDA SAT', data: '19' },
      { title: 'RFC EMISOR CTA. ORD. SAT', data: '20' },
      { title: 'NOMBRE DE BANCO ORD. EXT. SAT', data: '21' },
      { title: 'CTA. ORDENANTE SAT', data: '22' },
      { title: 'RFC EMISOR CTA. BEN. SAT', data: '23' },
      { title: 'CTA. BENEFICIARIO SAT', data: '24' },
      { title: 'DOCUMENTO RELACIONADO', data: '25' },
      { title: 'IMPORTE PAGADO', data: '26' },
      { title: 'IMPORTE SALDO', data: '27' },
      { title: 'IMPORTE INSOLUTO', data: '28' },
      { title: 'MÉTODO DE PAGO DR SAT', data: '29' },
      { title: 'TIPO DE CAMBIO SAT', data: '30' },
      { title: 'TIPO DE CAMBIO DR SAT', data: '31' },
      { title: 'NÚMERO DE PARCIALIDAD SAT', data: '32' },
      { title: 'SERIE DR SAT', data: '33' },
      { title: 'FOLIO DR SAT', data: '34' },
      { title: 'MONEDA DR SAT', data: '35' },
      { title: 'HORA SAT', data: '36' },
      { title: 'VERSIÓN SAT', data: '37' },
      { title: 'NÚMERO DE TRANSACCIÓN FACTO', data: '38' },
      { title: 'FECHA DE TRANSACCIÓN FACTO', data: '39' },
      { title: 'FOLIO FISCAL FACTO', data: '40' },
      { title: 'ESTATUS FACTO', data: '41' },
      { title: 'FORMA DE PAGO FACTO', data: '42' },
      { title: 'NÚMERO DE PARCIALIDAD FACTO', data: '43' },
      { title: 'RFC EMISOR FACTO', data: '44' },
      { title: 'RFC RECEPTOR FACTO', data: '45' },
      { title: 'SISTEMA EMISOR FACTO', data: '46' },
      { title: 'RFC PAC FACTO', data: '47' },
      { title: 'TIPO DE DOCUMENTO FISCAL FACTO', data: '48' },
      { title: 'SERIE FACTO', data: '49' },
      { title: 'FOLIO FACTO', data: '50' },
      { title: 'MONEDA FACTO', data: '51' },
      { title: 'TIPO DE CAMBIO FACTO', data: '52' },
      { title: 'MONTO FACTO', data: '53' },
      { title: 'FECHA DE PAGO FACTO', data: '54' },
      { title: 'FECHA FACTURA FACTO (YYYY-MM-DD)', data: '55' },
      { title: 'FECHA FACTURA  FACTO', data: '56' },
      { title: 'FECHA TIMBRADO FACTO', data: '57' },
      { title: 'FECHA CANCELACIÓN FACTO', data: '58' }
    ];

  }
}

export class ColumnsPagosEmiFaltantes {
  columns_header: Array<{ title: string, data: string }>;

  constructor() {
    this.columns_header = [
      { title: 'NÚMERO DE TRANSACCIÓN FACTO', data: '0' },
      { title: 'FECHA DE TRANSACCIÓN FACTO', data: '1' },
      { title: 'FOLIO FISCAL FACTO', data: '2' },
      { title: 'ESTATUS FACTO', data: '3' },
      { title: 'FORMA DE PAGO FACTO', data: '4' },
      { title: 'NÚMERO DE PARCIALIDAD FACTO', data: '5' },
      { title: 'RFC EMISOR FACTO', data: '6' },
      { title: 'RFC RECEPTOR FACTO', data: '7' },
      { title: 'SISTEMA EMISOR FACTO', data: '8' },
      { title: 'RFC PAC FACTO', data: '9' },
      { title: 'TIPO DE DOCUMENTO FISCAL FACTO', data: '10' },
      { title: 'SERIE FACTO', data: '11' },
      { title: 'FOLIO FACTO', data: '12' },
      { title: 'MONEDA FACTO', data: '13' },
      { title: 'TIPO DE CAMBIO FACTO', data: '14' },
      { title: 'MONTO FACTO', data: '15' },
      { title: 'FECHA DE PAGO FACTO', data: '16' },
      { title: 'FECHA FACTURA FACTO (YYYY-MM-DD)', data: '17' },
      { title: 'FECHA FACTURA FACTO', data: '18' },
      { title: 'FECHA TIMBRADO FACTO', data: '19' },
      { title: 'FECHA CANCELACIÓN FACTO', data: '20' }
    ];
  }
}

export class ColumnsPagosEmiDescuadre {
  columns_header: Array<{ title: string, data: string }>;

  constructor() {
    this.columns_header = [
      { title: 'ESTATUS SAT', data: '0' },
      { title: 'FECHA CANCELACIÓN SAT', data: '1' },
      { title: 'FOLIO FISCAL SAT', data: '2' },
      { title: 'RFC EMISOR SAT', data: '3' },
      { title: 'RAZÓN SOCIAL EMISOR SAT', data: '4' },
      { title: 'RFC RECEPTOR SAT', data: '5' },
      { title: 'RAZÓN SOCIAL RECEPTOR SAT', data: '6' },
      { title: 'RFC PAC SAT', data: '7' },
      { title: 'FECHA EMISION SAT (YYYY-MM-DD)', data: '8' },
      { title: 'FECHA EMISION SAT', data: '9' },
      { title: 'FECHA TIMBRADO SAT', data: '10' },
      { title: 'MONTO DE PAGO SAT', data: '11' },
      { title: 'EFECTO COMPROBANTE SAT', data: '12' },
      { title: 'USO DE CFDI SAT', data: '13' },
      { title: 'CÓDIGO POSTAL EMISOR SAT', data: '14' },
      { title: 'FOLIO SAT', data: '15' },
      { title: 'SERIE SAT', data: '16' },
      { title: 'FECHA PAGO SAT (YYYY-MM-DD)', data: '17' },
      { title: 'FORMA DE PAGO SAT ', data: '18' },
      { title: 'MONEDA SAT', data: '19' },
      { title: 'RFC EMISOR CTA. ORD. SAT', data: '20' },
      { title: 'NOMBRE DE BANCO ORD. EXT. SAT', data: '21' },
      { title: 'CTA. ORDENANTE SAT', data: '22' },
      { title: 'RFC EMISOR CTA. BEN. SAT', data: '23' },
      { title: 'CTA. BENEFICIARIO SAT', data: '24' },
      { title: 'DOCUMENTO RELACIONADO', data: '25' },
      { title: 'IMPORTE PAGADO', data: '26' },
      { title: 'IMPORTE SALDO', data: '27' },
      { title: 'IMPORTE INSOLUTO', data: '28' },
      { title: 'MÉTODO DE PAGO DR SAT', data: '29' },
      { title: 'TIPO DE CAMBIO SAT', data: '30' },
      { title: 'TIPO DE CAMBIO DR SAT', data: '31' },
      { title: 'NÚMERO DE PARCIALIDAD SAT', data: '32' },
      { title: 'SERIE DR SAT', data: '33' },
      { title: 'FOLIO DR SAT', data: '34' },
      { title: 'MONEDA DR SAT', data: '35' },
      { title: 'HORA SAT', data: '36' },
      { title: 'VERSIÓN SAT', data: '37' },
      { title: 'NÚMERO DE TRANSACCIÓN FACTO', data: '38' },
      { title: 'FECHA DE TRANSACCIÓN FACTO', data: '39' },
      { title: 'FOLIO FISCAL FACTO', data: '40' },
      { title: 'ESTATUS FACTO', data: '41' },
      { title: 'FORMA DE PAGO FACTO', data: '42' },
      { title: 'NÚMERO DE PARCIALIDAD FACTO', data: '43' },
      { title: 'RFC EMISOR FACTO', data: '44' },
      { title: 'RFC RECEPTOR FACTO', data: '45' },
      { title: 'SISTEMA EMISOR FACTO', data: '46' },
      { title: 'RFC PAC FACTO', data: '47' },
      { title: 'TIPO DE DOCUMENTO FISCAL FACTO', data: '48' },
      { title: 'SERIE FACTO', data: '49' },
      { title: 'FOLIO FACTO', data: '50' },
      { title: 'MONEDA FACTO', data: '51' },
      { title: 'TIPO DE CAMBIO FACTO', data: '52' },
      { title: 'MONTO FACTO', data: '53' },
      { title: 'FECHA DE PAGO FACTO', data: '54' },
      { title: 'FECHA FACTURA FACTO (YYYY-MM-DD)', data: '55' },
      { title: 'FECHA FACTURA  FACTO', data: '56' },
      { title: 'FECHA TIMBRADO FACTO', data: '57' },
      { title: 'FECHA CANCELACIÓN FACTO', data: '58' },
      { title: 'DESCUADRE', data: '59' }
    ];
  }
}
